name: CI

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
    - uses: env.GITHUB_WORKSPACE
      with: 
        gisturl: "d8dedd5f430521a1ae1af8c2d73c46eb"
